
services:
  database:
    container_name: postgres-sql-tp-uno
    image: postgres
    networks:
      - tp-uno-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/data-postgres:/var/lib/postgresql/data

networks:
  tp-uno-net:
    external: true